#Range: 0.0 ~ 2.147483647E9
SteamTurbineGeneratePerSteam = 3.5
#Range: 0.0 ~ 96000.0
ElectrodeCost = 0.25
#Range: 0.0 ~ 2.147483647E9
CrucibleCooldownRate = 0.25
#Range: 0.0 ~ 1.0
SteamTurbineSaturationPerSteam = 2.0E-6
#Range: 0.0 ~ 1.0
SteamTurbineUnsaturationPerTickPerLevel = 2.4E-4
#Range: 0.0 ~ 100000.0
SteamTurbineMinimumSaturation = 0.4
#Range: 0.0 ~ 100000.0
SteamTurbineMaximumSaturation = 4.0
#Range: > 0
SteamTurbineMaximumInput = 288
#Range: > 0
SteamTurbineMinimumInput = 48
#Range: 0.0 ~ 2.147483647E9
ElectrolyzerBaseTickEnergyRate = 1.0
#Range: 0.0 ~ 2.147483647E9
RotaryKilnBaseTickEnergyRate = 2.0
#Range: 0.0 ~ 2.147483647E9
CarKilnBaseTickEnergyRate = 4.0
#Range: 0.0 ~ 2.147483647E9
ChemicalReactorBaseTickEnergyRate = 1.0